#!/bin/bash

TARGET=mongo-c-driver-1.17.6
TARGET_TAR=${TARGET}.tar.gz

tar -zxvf ${TARGET_TAR}
mv $TARGET mongoc
mkdir -p mongoc/cmake-build
cd mongoc/cmake-build/
time cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF -DENABLE_CLIENT_SIDE_ENCRYPTION=OFF -DENABLE_EXAMPLES=OFF -DENABLE_EXTRA_ALIGNMENT=OFF -DENABLE_ICU=OFF -DENABLE_MONGODB_AWS_AUTH=OFF -DENABLE_PIC=OFF -DENABLE_SASL=OFF -DENABLE_SHM_COUNTERS=OFF -DENABLE_SNAPPY=OFF -DENABLE_SRV=OFF -DENABLE_SSL=OFF -DENABLE_TESTS=OFF -DENABLE_UNINSTALL=OFF -DENABLE_ZLIB=OFF -DENABLE_ZSTD=OFF ..
time make